# EXPLORATORY DATA ANALYSIS(EDA)

In [ ]:
=====================EDA================
1) pandas   : data frame operations
2)numpy    : math operations
3)matplotlib    : plotting or graphs
4) seaborn    :   plotting or graphs
5)plotly     :   plotting or graphs
6)bokhe     :  plotting or graphs

=====================Machine Learning===================
7) sickit-learn(sklearn)   :  For all ML algorithms
8) stats      :   some statistical operations

=====================Deep Learning==================
9)tensorflow   : deep learning models(google)
10)keras       :  deep learning tensorflow as backend
11)pytorch      : deep learning models  
12) opencv     :   image and video operations
13)pillow        :  image operations

=====================Object detection models(transfer learning)==================
14) mobilenet      :     deep learning packages only
15) VGGnet         :     deep learning packages only
16) Resnet         :     deep learning packages only
17) Inceptionv3     :     deep learning packages only
18) YOLO            :     deep learning packages only

====================Natural Languaage Processing=========================
19)    NLTK       :  Natural language tool kit
20) spCy          :  Alternative to NLTK
21)WordCloud      :  Text Representation

=======================NLP word Embedding Models=========================
22)Word2vec    : Google
23)GloVe       : Stanford
24)Fasttext     : Meta

=======================ALLEN NLP(organization)================================
25) NLP applications   :    Pyspark as backend

=======================Optical Character Recognisation(OCR)=====================
    Extarct text from image
26)Tesseract
27)easyocr

===================================BERT=================================
BERT: Bi directional Encoded Representations from tansformers
28) Transformers    :  hugging face(Google)

==================================WebScrapping=======================
29) SQLITE     : connect the database using python
30)Selenium    :
31)Beautiful soup
32)Regex

===========================GenAI and LLM================================
33)Langchain      : To connect all LLm models
34) Gpt     :    openAi
35)gemini:      Google
36) Llama         : Meta
37) Grok      :  XAi
38)BedRock     : Amazon
39) claude Ai  :  Anthropic

=======================Agentic AI =============================
40) Langraph
41)  CrewAI
42) Phidata
43) Autogen

=========================API creation ==========================
44) Flask
45) fast API
46) gradio
47) Django

=======================webApplication ===========================
48) Streamlit

===========================Model deployment ===========================
49)mlflow
50)Kubeflow

======================== Cloud AI ==================================
51) Azure Cognitive services
52)Azure ML studio
53)GCP vertexAI
54)AWS Sagemaker

========================Extra =========================
55) random
56) time
57) math
58) loggings
59) warnings
60) date

**Step-1: Import packages**

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Step-2:Create a Dataframe using list**

In [11]:
names=['ram','shyam','prem']
pd.DataFrame(names)

       0
0    ram
1  shyam
2   prem

In [13]:
names=['ram','shyam','prem']
age=[20,30,40]
pd.DataFrame(names,age)

        0
20    ram
30  shyam
40   prem

In [15]:
names=['ram','shyam','prem']
age=[20,30,40]
pd.DataFrame(zip(names,age))

       0   1
0    ram  20
1  shyam  30
2   prem  40

In [17]:
names=['ram','shyam','prem']
age=[20,30,40]
city=['hyd','bnglr','pune']
pd.DataFrame(zip(names,age,city))

       0   1      2
0    ram  20    hyd
1  shyam  30  bnglr
2   prem  40   pune

**Step-3:Add the column**

In [22]:
names=['ram','shyam','prem']
pd.DataFrame(names,columns=['Names'])

   Names
0    ram
1  shyam
2   prem

In [26]:
names=['ram','shyam','prem']
age=[20,30,40]
city=['hyd','bnglr','pune']
pd.DataFrame(zip(names,age,city),columns=['Names','Age','City'])

   Names  Age   City
0    ram   20    hyd
1  shyam   30  bnglr
2   prem   40   pune

In [ ]:
**Step-4:Modify the index**

In [88]:
names=['ram','shyam','prem']
age=[20,30,40]
city=['hyd','bnglr','pune']
df1=pd.DataFrame(zip(names,age,city),index=['A','B','C'],columns=['Names','Age','City'])

In [36]:
df1

   Names  Age   City
a    ram   20    hyd
b  shyam   30  bnglr
c   prem   40   pune

In [38]:
type(df1)

pandas.core.frame.DataFrame

- index length should match with no. of rows
- columns length should be match with no. of cols

**Step-4:Create a Dataframe using Dictonary**

In [46]:
names=['ram','shyam','prem']
age=[20,30,40]
city=['hyd','bnglr','pune']

d={'Names':['Ram','Prem','Shyam'],
    'Age':[20,30,40],
     'City':['hyd','pune','bnglr']}
pd.DataFrame(d,index=['A','B','C'])

#Keys behave as colums
# No need to mention explicitly

   Names  Age   City
A    Ram   20    hyd
B   Prem   30   pune
C  Shyam   40  bnglr

**Step-6:Create a Scalar Quantity using Dictonry(Single values)**

In [54]:
d={'Names':'Ram',
    'Age':20,
     'City':'hyd'}
pd.DataFrame(d,index=[1])

  Names  Age City
1   Ram   20  hyd

**Step-7:Data quick checks**
- shape
- size
- len
- columns
- dtypes

In [61]:
df1.shape

(3, 3)

In [63]:
df1.size

9

In [67]:
df1.len

AttributeError: 'DataFrame' object has no attribute 'length'

In [69]:
df1.columns

Index(['Names', 'Age', 'City'], dtype='object')

In [72]:
df1.dtypes

Names    object
Age       int64
City     object
dtype: object

**Step-8:Add the data to Empty dataframe**

In [18]:
d1=pd.DataFrame()
d1['Names']=['Ram','Prem','Shyam']
d1['Age']=[12,14,15]
d1

   Names  Age
0    Ram   12
1   Prem   14
2  Shyam   15

**Ste-9:Add data to Already existed dataframe**
- we want to add marks to already existed data fram(df1)

In [148]:
df1['Marks']=[100,99,80]
df1

   Names  Age   City  Marks
A    ram   20    hyd    100
B  shyam   30  bnglr     99
C   prem   40   pune     80

**Step-10:Updating the column values**
- if u wnt to add new column to empty dataframe..
- or if u want to add new column to existed DF
- or if u want to modify the adat of a specific column
- syntax is asame

In [33]:
df1

   Names  Age   City  Marks
a    ram   20    hyd    100
b  shyam   30  bnglr     99
c   prem   40   pune     80

In [39]:
df1['City']=['mumbai','chennai','agra']
df1['city']=['mumbai','chennai','agra']
df1

   Names  Age     City  Marks     city
a    ram   20   mumbai    100   mumbai
b  shyam   30  chennai     99  chennai
c   prem   40     agra     80     agra

**Step-11:How to drop the specific column**
- by default axis=0 represents index
- if u provide the column change axis=1
- inplace =True ..then dataframe will be saved

In [77]:
df1.drop('city',axis=1,inplace=True)

In [79]:
df1

   Names  Age     City  Marks
a    ram   20   mumbai    100
b  shyam   30  chennai     99
c   prem   40     agra     80

In [90]:
df1['age']=[20,30,40]
df1

   Names  Age   City  age
A    ram   20    hyd   20
B  shyam   30  bnglr   30
C   prem   40   pune   40

In [94]:
df1.drop(columns='age',inplace=True)

In [96]:
df1

   Names  Age   City
A    ram   20    hyd
B  shyam   30  bnglr
C   prem   40   pune

In [116]:
df1['age']=[20,30,40]
df1['city']=['raipole','ibp','secbad']
df1

   Names  Age   City  age     city
A    ram   20    hyd   20  raipole
B  shyam   30  bnglr   30      ibp
C   prem   40   pune   40   secbad

In [118]:
df1.drop(columns=['city','age'])

   Names  Age   City
A    ram   20    hyd
B  shyam   30  bnglr
C   prem   40   pune

In [130]:
df1.drop(['A'])

   Names  Age   City  age    city
B  shyam   30  bnglr   30     ibp
C   prem   40   pune   40  secbad

**Step-12:Rename the column**
- create a dictionary first
- key as old name and value as new name

In [138]:
dict1={'Age':'Living Age'}
df1.rename(dict1,axis=1)

   Names  Living Age   City  age     city
A    ram          20    hyd   20  raipole
B  shyam          30  bnglr   30      ibp
C   prem          40   pune   40   secbad

In [140]:
dict1={'City':'Place'}
df1.rename(columns=dict1)

   Names  Age  Place  age     city
A    ram   20    hyd   20  raipole
B  shyam   30  bnglr   30      ibp
C   prem   40   pune   40   secbad

In [144]:
df1.drop(['age','city'],axis=1,inplace=True)

In [150]:
df1

   Names  Age   City  Marks
A    ram   20    hyd    100
B  shyam   30  bnglr     99
C   prem   40   pune     80

**Step-13:Add a new row**

In [155]:
df1.loc['D']=['sita',24,'agra',56]
df1

   Names  Age   City  Marks
A    ram   20    hyd    100
B  shyam   30  bnglr     99
C   prem   40   pune     80
D   sita   24   agra     56

In [159]:
df1.drop(labels='D',inplace)

   Names  Age   City  Marks
A    ram   20    hyd    100
B  shyam   30  bnglr     99
C   prem   40   pune     80

**Step-14:Save the dataframe**

In [162]:
df1

   Names  Age   City  Marks
A    ram   20    hyd    100
B  shyam   30  bnglr     99
C   prem   40   pune     80
D   sita   24   agra     56

In [164]:
df1.to_csv('owndata.csv')

**Step-15:Read the dataframe**

In [177]:
pd.read_csv('owndata.csv')

  Unnamed: 0  Names  Age   City  Marks
0          A    ram   20    hyd    100
1          B  shyam   30  bnglr     99
2          C   prem   40   pune     80
3          D   sita   24   agra     56

In [183]:
df1.to_csv('owndata1.csv',index=False)

In [185]:
pd.read_csv('owndata1.csv')

   Names  Age   City  Marks
0    ram   20    hyd    100
1  shyam   30  bnglr     99
2   prem   40   pune     80
3   sita   24   agra     56

In [195]:
df1.to_excel('owndata2.xlsx',index=False)
pd.read_excel('owndata2.xlsx')

   Names  Age   City  Marks
0    ram   20    hyd    100
1  shyam   30  bnglr     99
2   prem   40   pune     80
3   sita   24   agra     56

In [205]:
pd.read_csv(r"C:\Users\achin\Downloads\DataSets(Nareshit)\bank.csv")

     age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0     30;"unemployed";"married";"primary";"no";1787;...
1     33;"services";"married";"secondary";"no";4789;...
2     35;"management";"single";"tertiary";"no";1350;...
3     30;"management";"married";"tertiary";"no";1476...
4     59;"blue-collar";"married";"secondary";"no";0;...
...                                                 ...
4516  33;"services";"married";"secondary";"no";-333;...
4517  57;"self-employed";"married";"tertiary";"yes";...
4518  57;"technician";"married";"secondary";"no";295...
4519  28;"blue-collar";"married";"secondary";"no";11...
4520  44;"entrepreneur";"single";"tertiary";"no";113...

[4521 rows x 1 columns]

In [209]:
pd.read_csv(r"C:\Users\achin\Downloads\DataSets(Nareshit)\Visadataset.csv")

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified