- In pandas we can join two dataframes
  - merge
  - join
  - concat

In [3]:
import pandas as pd

In [9]:
d1={'ID':[1,2,3],
    'Name':["Ram","Shyam","Prem"]}
d2={'ID':[1,2,4],
    'Age':[20,25,30]}
df1=pd.DataFrame(d1)
df2=pd.DataFrame(d2)

In [15]:
pd.merge(df1,df2,on='ID',how='inner')

   ID   Name  Age
0   1    Ram   20
1   2  Shyam   25

In [17]:
pd.merge(df1,df2,on='ID',how='outer')

   ID   Name   Age
0   1    Ram  20.0
1   2  Shyam  25.0
2   3   Prem   NaN
3   4    NaN  30.0

In [19]:
pd.merge(df1,df2,on='ID',how='left')

   ID   Name   Age
0   1    Ram  20.0
1   2  Shyam  25.0
2   3   Prem   NaN

In [21]:
pd.merge(df1,df2,on='ID',how='right')

   ID   Name  Age
0   1    Ram   20
1   2  Shyam   25
2   4    NaN   30