**Missing Values**

In [3]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',np.nan],
     'Age':[np.nan,22,25,27],
     'City':['Pune','Pune',np.nan,'Hyd']}
df=pd.DataFrame(Data)
df

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [4]:
df.to_csv('data_missing.csv',index=False)

In [5]:
pd.read_csv('data_missing.csv')

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [6]:


import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',None],
     'Age':[None,22,25,27],
     'City':['Pune','Pune',None,'Hyd']}
df1=pd.DataFrame(Data)
df1

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  None
3     None  27.0   Hyd

In [7]:

df1.to_csv('data_missing1.csv',index=False)

In [8]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

In [9]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

**isnull**

In [11]:
df.isnull()

   Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [12]:
df.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**fillna**

In [14]:
df.fillna(30) ## Abd tech

     Names   Age  City
0   Ramesh  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0    30
3       30  27.0   Hyd

**diff bw nan and none**

In [16]:
np.nan+5

nan

In [21]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [ ]:
we cant repleace any value in none place

In [ ]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,None,3])

In [ ]:
arr1

In [ ]:
np.nansum(arr1),np.sum(arr1)

In [25]:
np.sum(arr2)

NameError: name 'arr2' is not defined

**Filling based on cols**

In [30]:
df['Names'].fillna('prashanth')

0       Ramesh
1       Suresh
2      Sathish
3    prashanth
Name: Names, dtype: object

- pad
- bfill
- ffill
- backfill

In [33]:
df.fillna(method='pad') # fills based on vlaue below it..if not exists..thgen nan

C:\Users\achin\AppData\Local\Temp\ipykernel_24348\1021240182.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad') # fills based on vlaue below it..if not exists..thgen nan

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [35]:
df.fillna(method='bfill')  # fills based on vlaue above it..if not exists..thgen nan

C:\Users\achin\AppData\Local\Temp\ipykernel_24348\751390696.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')  # fills based on vlaue above it..if not exists..thgen nan

     Names   Age  City
0   Ramesh  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

In [37]:
df.fillna(method='ffill')  # fills based on vlaue below it..if not exists..thgen nan

C:\Users\achin\AppData\Local\Temp\ipykernel_24348\4154251956.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')  # fills based on vlaue below it..if not exists..thgen nan

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [39]:

df.fillna(method='backfill')  # fills based on vlaue above it..if not exists..thgen nan

C:\Users\achin\AppData\Local\Temp\ipykernel_24348\706515840.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='backfill')  # fills based on vlaue above it..if not exists..thgen nan

     Names   Age  City
0   Ramesh  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

- Ideas:filling avlues with random==df.fillname(<random>)
-     : based on column===df{<col>}.fillname[<random>]
-   : using some pattern of method====df.fillna[<method>]
-     : using m-m-m=====df.fillname(m or-m or-m)
-    :avg value using neighbours data
-    : base on correlation of another cols

**Mean median Mode**

In [47]:
age_mean=df['Age'].mean()
print('age_mean:',age_mean)
df['Age'].fillna(age_mean)

age_mean: 24.666666666666668

0    24.666667
1    22.000000
2    25.000000
3    27.000000
Name: Age, dtype: float64

In [74]:
city_mode=df['City'].mode()
df['City'].fillna(city_mode)

0    Pune
1    Pune
2     NaN
3     Hyd
Name: City, dtype: object

In [55]:
city_mode.values[0]

'Pune'

**Impute class**

In [68]:
from sklearn import impute

In [70]:
dir(impute)

['KNNImputer',
 'MissingIndicator',
 'SimpleImputer',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_knn',
 'typing']

**KNN Imputer**

- k-nearest neighbours
- k= hyper parameter means user can change
- Idea:Instead of taking all sample savg..
  - first fix neighbours numbers as k
  - then using distance formula..find neighbours
  -then take average of thise sanpleto find missing value

In [86]:
import numpy as np
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(X)

     0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [88]:
imputer=KNNImputer(n_neighbors=2,weights='distance')
imputer.fit_transform(X)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])